/**
 * LeadPulse AI - Comprehensive B2B Prospect Mock Database v2
 * Rich, verified leads across SaaS, Fintech, E-Commerce, AI, HealthTech & Agencies.
 * Now includes: sourcePlatform, emailStatus, mxValid, smtpCheck, fundingStage fields.
 */

export const INITIAL_LEADS = [
  // ── LINKEDIN SOURCED ──────────────────────────────────────────────────────
  {
    id: "lead_001",
    name: "Elena Rostova",
    title: "Chief Executive Officer & Co-Founder",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #6366F1, #8B5CF6)",
    company: "Synapse Dynamics",
    domain: "synapsedynamics.ai",
    industry: "AI & ML",
    companySize: "51-200",
    headcount: 85,
    revenue: "$14.5M ARR",
    fundingStage: "Series A",
    location: "San Francisco, US",
    region: "North America",
    email: "elena.rostova@synapsedynamics.ai",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.2,
    phone: "+1 (415) 892-4102",
    linkedin: "https://linkedin.com/in/elena-rostova-synapse",
    twitterHandle: "@elena_ai",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/elena-rostova-synapse",
    aiScore: 98,
    scoreTier: "ultra",
    intentSignal: "Secured $22M Series A led by Andreessen Horowitz; actively hiring 20+ ML engineers and sales leads",
    intentCategory: "funding",
    techStack: ["OpenAI API", "AWS Bedrock", "Salesforce", "Segment", "HubSpot", "Next.js"],
    companyBio: "Enterprise LLM orchestrator helping Fortune 500 banks automate compliance workflows with high precision.",
    recentNews: "Named Top 10 Enterprise AI Startup of 2026. Doubled customer base in Q2.",
    pipelineStage: "discovered",
    saved: true
  },
  {
    id: "lead_002",
    name: "Marcus Sterling",
    title: "VP of Global Sales & Growth",
    seniority: "VP/Director",
    avatarBg: "linear-gradient(135deg, #3B82F6, #1D4ED8)",
    company: "CloudScale Infra",
    domain: "cloudscale.io",
    industry: "B2B SaaS",
    companySize: "201-500",
    headcount: 320,
    revenue: "$48M ARR",
    fundingStage: "Series B",
    location: "Austin, US",
    region: "North America",
    email: "m.sterling@cloudscale.io",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.4,
    phone: "+1 (512) 671-8890",
    linkedin: "https://linkedin.com/in/marcus-sterling-sales",
    twitterHandle: "@marcus_scale",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/marcus-sterling-sales",
    aiScore: 96,
    scoreTier: "ultra",
    intentSignal: "Expanding into EMEA region; evaluating enterprise prospecting and sales intelligence tools",
    intentCategory: "tech_expansion",
    techStack: ["Kubernetes", "AWS", "Datadog", "Salesforce CRM", "Marketo", "Gong"],
    companyBio: "Multi-cloud kubernetes governance and cost optimization platform for high-scale enterprise engineering teams.",
    recentNews: "Surpassed 500 enterprise customers; announced European HQ opening in London.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_003",
    name: "Aria Chen",
    title: "Chief Marketing Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #EC4899, #8B5CF6)",
    company: "LuxeCart Global",
    domain: "luxecart.co",
    industry: "E-Commerce",
    companySize: "51-200",
    headcount: 140,
    revenue: "$62M GMV",
    fundingStage: "Series B",
    location: "New York, US",
    region: "North America",
    email: "aria.chen@luxecart.co",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.4,
    phone: "+1 (212) 480-3312",
    linkedin: "https://linkedin.com/in/ariachen-cmo",
    twitterHandle: "@ariachen_nyc",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/ariachen-cmo",
    aiScore: 94,
    scoreTier: "high",
    intentSignal: "Switching marketing automation stack and expanding influencer & B2B retail partnerships",
    intentCategory: "tech_expansion",
    techStack: ["Shopify Plus", "Klaviyo", "Gorgias", "Stripe", "Attentive", "Google Ads"],
    companyBio: "Direct-to-consumer luxury home goods brand blending sustainable materials with modern Scandinavian design.",
    recentNews: "Featured in Vogue and Fast Company for climate-neutral supply chain.",
    pipelineStage: "contacted",
    saved: true
  },
  {
    id: "lead_004",
    name: "Vikram Malhotra",
    title: "Chief Technology Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #10B981, #059669)",
    company: "NexusPay Ledger",
    domain: "nexuspay.finance",
    industry: "Fintech",
    companySize: "51-200",
    headcount: 110,
    revenue: "$28M ARR",
    fundingStage: "Series B",
    location: "London, UK",
    region: "Europe",
    email: "v.malhotra@nexuspay.finance",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.1,
    phone: "+44 20 7946 0918",
    linkedin: "https://linkedin.com/in/vikram-malhotra-fintech",
    twitterHandle: "@vikram_fintech",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/vikram-malhotra-fintech",
    aiScore: 95,
    scoreTier: "high",
    intentSignal: "Raised £15M Series B for pan-European cross-border merchant payments expansion",
    intentCategory: "funding",
    techStack: ["Stripe Connect", "Plaid", "Go", "PostgreSQL", "Terraform", "Mixpanel"],
    companyBio: "Real-time B2B payment rails and FX treasury automation for global cross-border marketplaces.",
    recentNews: "Granted FCA full electronic money institution license in the UK.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_005",
    name: "Sophie Dubois",
    title: "Head of Talent & People Operations",
    seniority: "Head/Manager",
    avatarBg: "linear-gradient(135deg, #F59E0B, #D97706)",
    company: "CyberShield Security",
    domain: "cybershield.de",
    industry: "Cybersecurity",
    companySize: "201-500",
    headcount: 240,
    revenue: "$36M ARR",
    fundingStage: "Series A",
    location: "Berlin, Germany",
    region: "Europe",
    email: "s.dubois@cybershield.de",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.0,
    phone: "+49 30 5679 4321",
    linkedin: "https://linkedin.com/in/sophie-dubois-hr",
    twitterHandle: "@sophie_cyber",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/sophie-dubois-hr",
    aiScore: 91,
    scoreTier: "high",
    intentSignal: "35% headcount surge over last 90 days; aggressively recruiting remote security analysts",
    intentCategory: "hiring",
    techStack: ["Okta", "CrowdStrike", "Workday", "Slack", "Lever", "Notion"],
    companyBio: "Zero-trust autonomous cloud detection and incident response system for regulated industries.",
    recentNews: "Closed enterprise contracts with 3 major European automotive conglomerates.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_006",
    name: "Liam O'Connor",
    title: "Founder & Managing Director",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #8B5CF6, #6D28D9)",
    company: "Apex Growth Labs",
    domain: "apexgrowth.agency",
    industry: "Digital Agency",
    companySize: "11-50",
    headcount: 38,
    revenue: "$7.2M Annual",
    fundingStage: "Bootstrap",
    location: "Toronto, CA",
    region: "North America",
    email: "liam@apexgrowth.agency",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.1,
    phone: "+1 (416) 902-8314",
    linkedin: "https://linkedin.com/in/liam-oconnor-apex",
    twitterHandle: "@liam_growth",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/liam-oconnor-apex",
    aiScore: 92,
    scoreTier: "high",
    intentSignal: "Looking to acquire new B2B client pipeline tools to serve 25+ retained tech clients",
    intentCategory: "product_launch",
    techStack: ["HubSpot Agency Partner", "Webflow", "Semrush", "Apollo", "Zapier"],
    companyBio: "Full-funnel B2B performance marketing and demand generation agency for Series A-C SaaS firms.",
    recentNews: "Ranked #4 on Fast50 Agencies in North America for 240% YoY client ARR growth.",
    pipelineStage: "meeting_booked",
    saved: true
  },
  {
    id: "lead_007",
    name: "Dr. Alistair Finch",
    title: "VP of Product & Clinical Informatics",
    seniority: "VP/Director",
    avatarBg: "linear-gradient(135deg, #06B6D4, #0891B2)",
    company: "PulseCare Health",
    domain: "pulsecare.med",
    industry: "HealthTech",
    companySize: "51-200",
    headcount: 125,
    revenue: "$19M ARR",
    fundingStage: "Series A",
    location: "Boston, US",
    region: "North America",
    email: "a.finch@pulsecare.med",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.4,
    phone: "+1 (617) 554-9021",
    linkedin: "https://linkedin.com/in/dr-alistair-finch",
    twitterHandle: "@alistair_health",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/dr-alistair-finch",
    aiScore: 89,
    scoreTier: "medium",
    intentSignal: "Received FDA Class II clearance; launching commercial hospital outreach across 40 states",
    intentCategory: "product_launch",
    techStack: ["Epic Systems Integrations", "AWS GovCloud", "Salesforce Health Cloud", "FHIR APIs"],
    companyBio: "Remote patient tele-monitoring and automated cardiovascular triage algorithms for acute care hospital networks.",
    recentNews: "Partnered with Mayo Clinic and Mass General for multi-center clinical validation study.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_008",
    name: "Kavita Raman",
    title: "Head of Demand Generation",
    seniority: "Head/Manager",
    avatarBg: "linear-gradient(135deg, #F43F5E, #BE123C)",
    company: "OmniFlow Automation",
    domain: "omniflow.io",
    industry: "B2B SaaS",
    companySize: "51-200",
    headcount: 95,
    revenue: "$16.8M ARR",
    fundingStage: "Series A",
    location: "Seattle, US",
    region: "North America",
    email: "kavita@omniflow.io",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.3,
    phone: "+1 (206) 430-7719",
    linkedin: "https://linkedin.com/in/kavita-raman-b2b",
    twitterHandle: "@kavita_demand",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/kavita-raman-b2b",
    aiScore: 97,
    scoreTier: "ultra",
    intentSignal: "Allocating $350k Q3 budget for outbound prospecting automation and CRM data enrichment",
    intentCategory: "tech_expansion",
    techStack: ["HubSpot Enterprise", "ZoomInfo", "Clearbit", "Segment", "Intercom", "Chili Piper"],
    companyBio: "No-code robotic process workflow builder connecting ERPs, CRMs, and accounting systems seamlessly.",
    recentNews: "Released version 4.0 with native autonomous AI agent connectors.",
    pipelineStage: "discovered",
    saved: true
  },
  {
    id: "lead_009",
    name: "Kenji Sato",
    title: "Chief Executive Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #6366F1, #3B82F6)",
    company: "Kurogane Robotics",
    domain: "kurogane-robotics.jp",
    industry: "AI & ML",
    companySize: "11-50",
    headcount: 45,
    revenue: "$8.4M ARR",
    fundingStage: "Series A",
    location: "Tokyo, Japan",
    region: "APAC",
    email: "kenji.sato@kurogane-robotics.jp",
    emailDeliverability: 96,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 96.0,
    phone: "+81 3 5555 0142",
    linkedin: "https://linkedin.com/in/kenji-sato-robotics",
    twitterHandle: "@kenji_robotics",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/kenji-sato-robotics",
    aiScore: 93,
    scoreTier: "high",
    intentSignal: "Closed ¥1.8B funding round; seeking US and European distribution and supply chain partners",
    intentCategory: "funding",
    techStack: ["ROS 2", "Nvidia Isaac", "GCP", "C++", "Python", "Atlassian Jira"],
    companyBio: "Autonomous mobile robots (AMRs) for warehouse fulfillment and smart factory logistics.",
    recentNews: "Deployed 300+ AMRs in Rakuten logistics centers across Kanto prefecture.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_010",
    name: "Jessica Albright",
    title: "Director of Enterprise Sales",
    seniority: "VP/Director",
    avatarBg: "linear-gradient(135deg, #10B981, #047857)",
    company: "PropTech Horizon",
    domain: "prophorizon.com",
    industry: "Real Estate",
    companySize: "51-200",
    headcount: 80,
    revenue: "$13.2M ARR",
    fundingStage: "Series A",
    location: "Miami, US",
    region: "North America",
    email: "j.albright@prophorizon.com",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.1,
    phone: "+1 (305) 782-9901",
    linkedin: "https://linkedin.com/in/jessica-albright-proptech",
    twitterHandle: "@jess_proptech",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/jessica-albright-proptech",
    aiScore: 90,
    scoreTier: "high",
    intentSignal: "Expanding commercial broker outreach tools following acquisition of Miami commercial portfolio",
    intentCategory: "hiring",
    techStack: ["Salesforce", "CoStar API", "Mapbox", "AWS", "Pendo"],
    companyBio: "AI-driven commercial real estate valuation, tenant underwriting, and leasing portfolio management software.",
    recentNews: "Integrated with MLS systems across Florida, Georgia, and Texas.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_011",
    name: "Mateo Silva",
    title: "Chief Information Security Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #8B5CF6, #EC4899)",
    company: "Fortress Zero",
    domain: "fortresszero.io",
    industry: "Cybersecurity",
    companySize: "201-500",
    headcount: 280,
    revenue: "$42M ARR",
    fundingStage: "Series B",
    location: "Chicago, US",
    region: "North America",
    email: "mateo@fortresszero.io",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.0,
    phone: "+1 (312) 890-4412",
    linkedin: "https://linkedin.com/in/mateo-silva-security",
    twitterHandle: "@mateo_sec",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/mateo-silva-security",
    aiScore: 95,
    scoreTier: "high",
    intentSignal: "Auditing third-party vendor access tools ahead of SOC2 Type II and FedRAMP certification",
    intentCategory: "tech_expansion",
    techStack: ["SentinelOne", "Splunk", "Azure AD", "Zscaler", "HashiCorp Vault"],
    companyBio: "Identity-first zero trust architecture platform safeguarding hybrid enterprise infrastructure.",
    recentNews: "Achieved FedRAMP In-Process status for US Federal agencies.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_012",
    name: "Chloe Dupont",
    title: "Head of Growth & Retention",
    seniority: "Head/Manager",
    avatarBg: "linear-gradient(135deg, #EC4899, #F43F5E)",
    company: "Velvet Bloom",
    domain: "velvetbloom.fr",
    industry: "E-Commerce",
    companySize: "11-50",
    headcount: 32,
    revenue: "$11M GMV",
    fundingStage: "Seed",
    location: "Paris, France",
    region: "Europe",
    email: "chloe.dupont@velvetbloom.fr",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.3,
    phone: "+33 1 42 68 55 10",
    linkedin: "https://linkedin.com/in/chloe-dupont-beauty",
    twitterHandle: "@chloedupont_fr",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/chloe-dupont-beauty",
    aiScore: 88,
    scoreTier: "medium",
    intentSignal: "Launching direct wholesale distribution to 500+ boutiques across UK and DACH region",
    intentCategory: "product_launch",
    techStack: ["Shopify Plus", "Klaviyo", "Gorgias", "Recharge", "Yotpo"],
    companyBio: "Clean organic botanical skincare line formulated with Mediterranean botanicals.",
    recentNews: "Won Best Indie Beauty Brand at Paris EcoBeauty Expo 2026.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_013",
    name: "David Vance",
    title: "VP of Engineering & DevOps",
    seniority: "VP/Director",
    avatarBg: "linear-gradient(135deg, #06B6D4, #3B82F6)",
    company: "HyperMesh Networks",
    domain: "hypermesh.net",
    industry: "Cloud Infrastructure",
    companySize: "500+",
    headcount: 750,
    revenue: "$110M ARR",
    fundingStage: "Series C",
    location: "Seattle, US",
    region: "North America",
    email: "d.vance@hypermesh.net",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.5,
    phone: "+1 (206) 912-3345",
    linkedin: "https://linkedin.com/in/david-vance-cloud",
    twitterHandle: "@dvance_devops",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/david-vance-cloud",
    aiScore: 94,
    scoreTier: "high",
    intentSignal: "Hiring 40+ distributed systems engineers following major global CDN rollout",
    intentCategory: "hiring",
    techStack: ["Rust", "eBPF", "Kubernetes", "AWS", "Grafana", "Cloudflare"],
    companyBio: "Edge computing mesh infrastructure that minimizes cross-continent API latency under 8ms.",
    recentNews: "Signed multi-year infrastructure agreement with top 3 streaming network.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_014",
    name: "Ananya Patel",
    title: "Founder & Chief Executive Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #10B981, #6366F1)",
    company: "FinVerse Global",
    domain: "finverse.sg",
    industry: "Fintech",
    companySize: "51-200",
    headcount: 65,
    revenue: "$15.4M ARR",
    fundingStage: "Series A",
    location: "Singapore",
    region: "APAC",
    email: "ananya.patel@finverse.sg",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.7,
    phone: "+65 6789 1234",
    linkedin: "https://linkedin.com/in/ananya-patel-finverse",
    twitterHandle: "@ananya_sg",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/ananya-patel-finverse",
    aiScore: 97,
    scoreTier: "ultra",
    intentSignal: "Raised $16M Series A; building localized sales teams across Singapore, Hong Kong and Sydney",
    intentCategory: "funding",
    techStack: ["PostgreSQL", "Go", "AWS AP-Southeast", "HubSpot", "Stripe", "Tableau"],
    companyBio: "Automated wealth management infrastructure and robo-advisory APIs for regional Asian banks.",
    recentNews: "Integrated with MAS Open Banking framework.",
    pipelineStage: "discovered",
    saved: true
  },
  {
    id: "lead_015",
    name: "Brandon Cole",
    title: "Chief Revenue Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #F59E0B, #EF4444)",
    company: "Veloce B2B Commerce",
    domain: "veloce.io",
    industry: "B2B SaaS",
    companySize: "201-500",
    headcount: 310,
    revenue: "$52M ARR",
    fundingStage: "Series C",
    location: "Denver, US",
    region: "North America",
    email: "b.cole@veloce.io",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.4,
    phone: "+1 (303) 540-6678",
    linkedin: "https://linkedin.com/in/brandon-cole-cro",
    twitterHandle: "@bcole_cro",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/brandon-cole-cro",
    aiScore: 96,
    scoreTier: "ultra",
    intentSignal: "Restructuring outbound SDR teams; evaluating AI-first cold email generation and lead enrichment stacks",
    intentCategory: "tech_expansion",
    techStack: ["Salesforce", "Salesloft", "ZoomInfo", "Gong.io", "Snowflake", "Datadog"],
    companyBio: "Next-generation CPQ and automated configure-price-quote engine for enterprise manufacturing.",
    recentNews: "Achieved 140% Net Revenue Retention (NRR) in FY25.",
    pipelineStage: "closed_won",
    saved: true
  },
  {
    id: "lead_016",
    name: "Nina Lindqvist",
    title: "VP of Product Marketing",
    seniority: "VP/Director",
    avatarBg: "linear-gradient(135deg, #06B6D4, #8B5CF6)",
    company: "NordicData Insights",
    domain: "nordicdata.se",
    industry: "B2B SaaS",
    companySize: "51-200",
    headcount: 90,
    revenue: "$17.5M ARR",
    fundingStage: "Series A",
    location: "Stockholm, Sweden",
    region: "Europe",
    email: "nina.l@nordicdata.se",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.2,
    phone: "+46 8 123 4567",
    linkedin: "https://linkedin.com/in/nina-lindqvist-saas",
    twitterHandle: "@nina_nordic",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/nina-lindqvist-saas",
    aiScore: 91,
    scoreTier: "high",
    intentSignal: "Launching product-led growth (PLG) self-serve tier to target North American mid-market",
    intentCategory: "product_launch",
    techStack: ["Mixpanel", "Segment", "HubSpot", "Intercom", "PostHog", "Stripe"],
    companyBio: "Automated business intelligence & data warehouse connector built specifically for non-technical managers.",
    recentNews: "Surpassed 1,200 paying teams in the Nordic and DACH markets.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_017",
    name: "Tariq Mansour",
    title: "Founder & Chief Executive Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #3B82F6, #10B981)",
    company: "Zest Logistics AI",
    domain: "zestlogistics.ae",
    industry: "AI & ML",
    companySize: "51-200",
    headcount: 75,
    revenue: "$12.8M ARR",
    fundingStage: "Series A",
    location: "Dubai, UAE",
    region: "Global",
    email: "tariq@zestlogistics.ae",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.6,
    phone: "+971 4 312 8890",
    linkedin: "https://linkedin.com/in/tariq-mansour-ai",
    twitterHandle: "@tariq_dubai",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/tariq-mansour-ai",
    aiScore: 94,
    scoreTier: "high",
    intentSignal: "Expanding autonomous fleet route optimization pilots into Saudi Arabia and Qatar",
    intentCategory: "tech_expansion",
    techStack: ["Python", "TensorFlow", "FastAPI", "PostGIS", "AWS ME-South", "Flutter"],
    companyBio: "AI fleet dispatch and cold-chain route prediction engine for Middle Eastern logistics operators.",
    recentNews: "Signed exclusive memorandum with Dubai Roads and Transport Authority.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_018",
    name: "Rachel Goldman",
    title: "Head of Growth & Partnerships",
    seniority: "Head/Manager",
    avatarBg: "linear-gradient(135deg, #EC4899, #F59E0B)",
    company: "CraftSupply Direct",
    domain: "craftsupply.co",
    industry: "E-Commerce",
    companySize: "11-50",
    headcount: 28,
    revenue: "$9.5M GMV",
    fundingStage: "Seed",
    location: "Portland, US",
    region: "North America",
    email: "rachel@craftsupply.co",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.0,
    phone: "+1 (503) 441-2890",
    linkedin: "https://linkedin.com/in/rachel-goldman-craft",
    twitterHandle: "@rachel_pdx",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/rachel-goldman-craft",
    aiScore: 89,
    scoreTier: "medium",
    intentSignal: "Launching wholesale marketplace portal for 3,000+ indie makers and boutiques",
    intentCategory: "product_launch",
    techStack: ["Shopify Plus", "Klaviyo", "Algolia", "Sanity CMS", "Stripe"],
    companyBio: "Curated raw materials and sustainable supplies marketplace for artisan creators and small brands.",
    recentNews: "Secured seed round from Collab Fund to scale artisan marketplace.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_019",
    name: "Felix Baumgartner",
    title: "Chief Technology Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #6366F1, #06B6D4)",
    company: "QuantumShield Crypt",
    domain: "quantumshield.ch",
    industry: "Cybersecurity",
    companySize: "11-50",
    headcount: 35,
    revenue: "$6.5M ARR",
    fundingStage: "Seed",
    location: "Zurich, Switzerland",
    region: "Europe",
    email: "f.baumgartner@quantumshield.ch",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.5,
    phone: "+41 44 215 9012",
    linkedin: "https://linkedin.com/in/felix-baumgartner-sec",
    twitterHandle: "@felix_crypto",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/felix-baumgartner-sec",
    aiScore: 93,
    scoreTier: "high",
    intentSignal: "Post-quantum encryption protocol validated by Swiss federal research institute; hiring enterprise sales team",
    intentCategory: "hiring",
    techStack: ["Rust", "C++", "OpenSSL", "Linux Kernel", "Docker", "GitLab CI"],
    companyBio: "Quantum-resistant public key infrastructure and encrypted communications for private banks.",
    recentNews: "Winner of the 2026 Swiss Cyber Excellence Award.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_020",
    name: "Morgan Lee",
    title: "Managing Partner",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #10B981, #3B82F6)",
    company: "Vanguard Marketing Collective",
    domain: "vanguardcollective.agency",
    industry: "Digital Agency",
    companySize: "11-50",
    headcount: 42,
    revenue: "$8.9M Annual",
    fundingStage: "Bootstrap",
    location: "Atlanta, US",
    region: "North America",
    email: "morgan@vanguardcollective.agency",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.2,
    phone: "+1 (404) 719-2234",
    linkedin: "https://linkedin.com/in/morgan-lee-vanguard",
    twitterHandle: "@morgan_agency",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/morgan-lee-vanguard",
    aiScore: 92,
    scoreTier: "high",
    intentSignal: "Expanding outbound SDR services for 12 corporate fintech clients; searching for accurate lead enrichment provider",
    intentCategory: "tech_expansion",
    techStack: ["HubSpot", "Clay", "Instantly", "Smartlead", "Airtable", "ClickUp"],
    companyBio: "High-touch outbound demand generation and pipeline acceleration agency for high-growth tech startups.",
    recentNews: "Generated over $40M in validated sales pipeline for clients in 2025.",
    pipelineStage: "contacted",
    saved: true
  },
  // ── TWITTER / X SOURCED ───────────────────────────────────────────────────
  {
    id: "lead_021",
    name: "Jake Thornton",
    title: "Founder & Growth Hacker",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #1DA1F2, #6366F1)",
    company: "ViralLoop SaaS",
    domain: "viralloop.io",
    industry: "B2B SaaS",
    companySize: "1-10",
    headcount: 7,
    revenue: "$1.2M ARR",
    fundingStage: "Seed",
    location: "New York, US",
    region: "North America",
    email: "jake@viralloop.io",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.0,
    phone: "+1 (646) 812-3390",
    linkedin: "https://linkedin.com/in/jakethornton-growth",
    twitterHandle: "@jakethornton_",
    sourcePlatform: "Twitter",
    sourceUrl: "https://twitter.com/jakethornton_",
    aiScore: 91,
    scoreTier: "high",
    intentSignal: "Tweeting about scaling PLG to 10k users; publicly looking for email outreach automation tools",
    intentCategory: "product_launch",
    techStack: ["HubSpot", "Stripe", "Intercom", "PostHog", "AWS"],
    companyBio: "Viral referral loop SaaS for early-stage startups. Helped 400+ companies achieve organic k-factor > 1.",
    recentNews: "Hit $1M ARR milestone with zero paid ads in 18 months.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_022",
    name: "Mei Lin",
    title: "CMO & Digital Strategist",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #1DA1F2, #EC4899)",
    company: "BoltMedia Agency",
    domain: "boltmedia.agency",
    industry: "Digital Agency",
    companySize: "11-50",
    headcount: 22,
    revenue: "$4.1M Annual",
    fundingStage: "Bootstrap",
    location: "Singapore",
    region: "APAC",
    email: "mei@boltmedia.agency",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.2,
    phone: "+65 8812 4490",
    linkedin: "https://linkedin.com/in/mei-lin-bolt",
    twitterHandle: "@mei_lin_bolt",
    sourcePlatform: "Twitter",
    sourceUrl: "https://twitter.com/mei_lin_bolt",
    aiScore: 89,
    scoreTier: "medium",
    intentSignal: "Posting about Q4 outbound campaigns for 15 B2B SaaS clients; seeking data providers",
    intentCategory: "tech_expansion",
    techStack: ["HubSpot", "Smartlead", "Clay", "Webflow", "Zapier", "Semrush"],
    companyBio: "Full-service B2B demand generation agency specializing in outbound for APAC tech companies.",
    recentNews: "Expanded client roster to include 5 Singapore-listed tech companies.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_023",
    name: "Ben Atkinson",
    title: "Co-Founder & CEO",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #1DA1F2, #10B981)",
    company: "FutureStack Labs",
    domain: "futurestack.dev",
    industry: "B2B SaaS",
    companySize: "1-10",
    headcount: 5,
    revenue: "$420K ARR",
    fundingStage: "Seed",
    location: "Austin, US",
    region: "North America",
    email: "ben@futurestack.dev",
    emailDeliverability: 96,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 96.0,
    phone: "+1 (512) 380-4921",
    linkedin: "https://linkedin.com/in/benatkinson-dev",
    twitterHandle: "@benatkinson_dev",
    sourcePlatform: "Twitter",
    sourceUrl: "https://twitter.com/benatkinson_dev",
    aiScore: 87,
    scoreTier: "medium",
    intentSignal: "Just launched beta; tweeting about developer tool traction — 3k signups in week 1",
    intentCategory: "product_launch",
    techStack: ["Next.js", "Supabase", "Vercel", "Stripe", "PostHog"],
    companyBio: "Developer-first API testing and collaboration platform for distributed engineering teams.",
    recentNews: "Featured in Product Hunt Daily with 1,200 upvotes on launch day.",
    pipelineStage: "discovered",
    saved: false
  },
  // ── UPWORK SOURCED ────────────────────────────────────────────────────────
  {
    id: "lead_024",
    name: "Patricia Morales",
    title: "Head of Operations",
    seniority: "Head/Manager",
    avatarBg: "linear-gradient(135deg, #6FDA44, #10B981)",
    company: "GlobalSource Partners",
    domain: "globalsource.co",
    industry: "Digital Agency",
    companySize: "11-50",
    headcount: 30,
    revenue: "$5.8M Annual",
    fundingStage: "Bootstrap",
    location: "Madrid, Spain",
    region: "Europe",
    email: "p.morales@globalsource.co",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.4,
    phone: "+34 91 4890 2211",
    linkedin: "https://linkedin.com/in/patricia-morales-ops",
    twitterHandle: "@patricia_gsrc",
    sourcePlatform: "Upwork",
    sourceUrl: "https://upwork.com/jobs/b2b-lead-generation-automation",
    aiScore: 90,
    scoreTier: "high",
    intentSignal: "Posted $15k Upwork project for B2B lead generation automation and CRM migration",
    intentCategory: "tech_expansion",
    techStack: ["HubSpot", "Salesforce", "Zapier", "Airtable", "Apollo"],
    companyBio: "EU-based sourcing and operations consultancy supporting enterprise procurement for global brands.",
    recentNews: "Onboarded 4 new Fortune 500 procurement clients in Q2.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_025",
    name: "James Okafor",
    title: "CEO & Founder",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #6FDA44, #6366F1)",
    company: "Apex Digital Solutions",
    domain: "apexdigital.ng",
    industry: "Digital Agency",
    companySize: "11-50",
    headcount: 25,
    revenue: "$3.2M Annual",
    fundingStage: "Bootstrap",
    location: "Abuja, Nigeria",
    region: "Global",
    email: "james@apexdigital.ng",
    emailDeliverability: 95,
    emailStatus: "Catch-All",
    mxValid: true,
    smtpCheck: false,
    deliverabilityScore: 71.0,
    phone: "+234 802 345 6789",
    linkedin: "https://linkedin.com/in/james-okafor-apex",
    twitterHandle: "@jamesokafor_ng",
    sourcePlatform: "Upwork",
    sourceUrl: "https://upwork.com/jobs/enterprise-outreach-campaign",
    aiScore: 86,
    scoreTier: "medium",
    intentSignal: "Hiring freelance team for enterprise outreach campaign targeting 500+ US tech companies",
    intentCategory: "hiring",
    techStack: ["Clay", "Instantly.ai", "Apollo", "HubSpot", "Google Workspace"],
    companyBio: "West African digital growth agency providing outbound, content, and CRM implementation.",
    recentNews: "Expanded agency team to serve clients in the US mid-market SaaS segment.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_026",
    name: "Arjun Mehta",
    title: "Founder",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #6FDA44, #3B82F6)",
    company: "CloudKart India",
    domain: "cloudkart.in",
    industry: "E-Commerce",
    companySize: "51-200",
    headcount: 95,
    revenue: "$18.5M GMV",
    fundingStage: "Series A",
    location: "Mumbai, India",
    region: "APAC",
    email: "arjun@cloudkart.in",
    emailDeliverability: 96,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 96.3,
    phone: "+91 98201 56789",
    linkedin: "https://linkedin.com/in/arjun-mehta-ck",
    twitterHandle: "@arjun_cloudkart",
    sourcePlatform: "Upwork",
    sourceUrl: "https://upwork.com/jobs/cold-email-sequence-developer",
    aiScore: 92,
    scoreTier: "high",
    intentSignal: "Upwork job post for cold email sequence developer; $25k/month email campaign planned",
    intentCategory: "tech_expansion",
    techStack: ["Shopify Plus", "Klaviyo", "Stripe", "Algolia", "AWS Mumbai"],
    companyBio: "India's fastest-growing B2B cloud accessories marketplace for enterprise hardware procurement.",
    recentNews: "Crossed 10,000 corporate buyers milestone; expanding to Southeast Asia in H2.",
    pipelineStage: "discovered",
    saved: false
  },
  // ── APOLLO / CUSTOM SCRAPER SOURCED ──────────────────────────────────────
  {
    id: "lead_027",
    name: "Raymond Chen",
    title: "Chief Growth Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #FF5C39, #8B5CF6)",
    company: "Quantum Scale AI",
    domain: "quantumscale.ai",
    industry: "AI & ML",
    companySize: "51-200",
    headcount: 90,
    revenue: "$20.3M ARR",
    fundingStage: "Series A",
    location: "San Francisco, US",
    region: "North America",
    email: "raymond.chen@quantumscale.ai",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.1,
    phone: "+1 (415) 320-7712",
    linkedin: "https://linkedin.com/in/raymond-chen-growth",
    twitterHandle: "@raymond_cgo",
    sourcePlatform: "Apollo",
    sourceUrl: "https://app.apollo.io/#/people?name=Raymond+Chen",
    aiScore: 97,
    scoreTier: "ultra",
    intentSignal: "Apollo signals: domain tech swap from Intercom to HubSpot; 3 new SDR hires on LinkedIn",
    intentCategory: "tech_expansion",
    techStack: ["HubSpot", "OpenAI API", "GCP", "Databricks", "Segment", "Gong"],
    companyBio: "Autonomous AI growth engine that replaces manual revenue operations with intelligent automation loops.",
    recentNews: "Signed 3-year enterprise deal with a top-5 US insurance carrier.",
    pipelineStage: "discovered",
    saved: true
  },
  {
    id: "lead_028",
    name: "Valentina Cruz",
    title: "VP of Revenue",
    seniority: "VP/Director",
    avatarBg: "linear-gradient(135deg, #FF5C39, #10B981)",
    company: "LatinoTech Hub",
    domain: "latinotech.mx",
    industry: "B2B SaaS",
    companySize: "51-200",
    headcount: 75,
    revenue: "$11.7M ARR",
    fundingStage: "Series A",
    location: "Mexico City, Mexico",
    region: "Global",
    email: "v.cruz@latinotech.mx",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.8,
    phone: "+52 55 6789 0123",
    linkedin: "https://linkedin.com/in/valentina-cruz-revenue",
    twitterHandle: "@valentina_ltmx",
    sourcePlatform: "Apollo",
    sourceUrl: "https://app.apollo.io/#/people?name=Valentina+Cruz",
    aiScore: 93,
    scoreTier: "high",
    intentSignal: "Apollo enrichment: recently switched CRM to Salesforce; actively hiring enterprise sales",
    intentCategory: "hiring",
    techStack: ["Salesforce", "HubSpot", "Outreach.io", "ZoomInfo", "Tableau"],
    companyBio: "B2B SaaS platform connecting 5,000+ Latin American startups with enterprise procurement pipelines.",
    recentNews: "Expanded operations to Colombia and Chile after 200% YoY ARR growth.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_029",
    name: "Mikkel Sørensen",
    title: "CEO & Co-Founder",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #FF5C39, #3B82F6)",
    company: "DanishScale SaaS",
    domain: "danishscale.dk",
    industry: "B2B SaaS",
    companySize: "51-200",
    headcount: 62,
    revenue: "$13.2M ARR",
    fundingStage: "Series A",
    location: "Copenhagen, Denmark",
    region: "Europe",
    email: "mikkel@danishscale.dk",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.6,
    phone: "+45 23 45 67 89",
    linkedin: "https://linkedin.com/in/mikkel-sorensen-saas",
    twitterHandle: "@mikkel_dkscale",
    sourcePlatform: "Apollo",
    sourceUrl: "https://app.apollo.io/#/people?name=Mikkel+S%C3%B8rensen",
    aiScore: 95,
    scoreTier: "high",
    intentSignal: "Apollo trigger: raised €8M Series A; Crunchbase funding event confirmed 3 days ago",
    intentCategory: "funding",
    techStack: ["HubSpot", "Stripe", "Vercel", "PostgreSQL", "Datadog", "Intercom"],
    companyBio: "Nordic B2B operations software helping 600+ companies automate invoicing and contract workflows.",
    recentNews: "Expanding to UK and DACH markets; hiring 15 enterprise AEs.",
    pipelineStage: "discovered",
    saved: false
  },
  // ── FACEBOOK SOURCED ──────────────────────────────────────────────────────
  {
    id: "lead_030",
    name: "Amanda Foster",
    title: "Chief Executive Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #1877F2, #EC4899)",
    company: "SunriseRetail Group",
    domain: "sunriseretail.com",
    industry: "E-Commerce",
    companySize: "51-200",
    headcount: 140,
    revenue: "$34.6M GMV",
    fundingStage: "Series A",
    location: "Phoenix, US",
    region: "North America",
    email: "amanda@sunriseretail.com",
    emailDeliverability: 96,
    emailStatus: "Catch-All",
    mxValid: true,
    smtpCheck: false,
    deliverabilityScore: 68.0,
    phone: "+1 (480) 771-8934",
    linkedin: "https://linkedin.com/in/amanda-foster-retail",
    twitterHandle: "@amanda_sunrise",
    sourcePlatform: "Facebook",
    sourceUrl: "https://facebook.com/sunriseretailgroup",
    aiScore: 88,
    scoreTier: "medium",
    intentSignal: "Facebook Business page shows massive ad spend increase for Q4; recruiting 20 sales staff",
    intentCategory: "hiring",
    techStack: ["Shopify Plus", "Meta Ads", "Klaviyo", "Gorgias", "Stripe"],
    companyBio: "Multi-brand e-commerce holding company operating 8 DTC brands across home, sports, and wellness verticals.",
    recentNews: "Acquired rival brand Desert Home Co. in $4.2M deal.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_031",
    name: "Emile Lacroix",
    title: "Managing Director",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #1877F2, #10B981)",
    company: "French Creative Collective",
    domain: "frcreative.fr",
    industry: "Digital Agency",
    companySize: "11-50",
    headcount: 35,
    revenue: "$6.1M Annual",
    fundingStage: "Bootstrap",
    location: "Lyon, France",
    region: "Europe",
    email: "emile@frcreative.fr",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.0,
    phone: "+33 4 72 81 90 12",
    linkedin: "https://linkedin.com/in/emile-lacroix-creative",
    twitterHandle: "@emile_frcreative",
    sourcePlatform: "Facebook",
    sourceUrl: "https://facebook.com/frenchcreativecollective",
    aiScore: 87,
    scoreTier: "medium",
    intentSignal: "Facebook profile shows new office opening and 5 senior creative director hires this month",
    intentCategory: "hiring",
    techStack: ["Figma", "Webflow", "HubSpot", "ClickUp", "Adobe CC"],
    companyBio: "Award-winning creative and branding studio serving luxury hospitality and fashion brands across Europe.",
    recentNews: "Won Grand Prix at Cannes Lions 2026 for best integrated brand campaign.",
    pipelineStage: "discovered",
    saved: false
  },
  // ── PINTEREST SOURCED ─────────────────────────────────────────────────────
  {
    id: "lead_032",
    name: "Sofia Martinez",
    title: "Brand Director & Co-Founder",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #E60023, #8B5CF6)",
    company: "Casa Bella Home Decor",
    domain: "casabella.co",
    industry: "E-Commerce",
    companySize: "11-50",
    headcount: 28,
    revenue: "$8.8M GMV",
    fundingStage: "Seed",
    location: "Barcelona, Spain",
    region: "Europe",
    email: "sofia@casabella.co",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.3,
    phone: "+34 93 265 4411",
    linkedin: "https://linkedin.com/in/sofia-martinez-brand",
    twitterHandle: "@sofia_casabella",
    sourcePlatform: "Pinterest",
    sourceUrl: "https://pinterest.com/casabellahomedecor",
    aiScore: 88,
    scoreTier: "medium",
    intentSignal: "Pinterest business account shows 2M monthly views; looking to monetize through B2B wholesale",
    intentCategory: "product_launch",
    techStack: ["Shopify Plus", "Pinterest Ads", "Klaviyo", "Gorgias", "Recharge"],
    companyBio: "Mediterranean-inspired luxury home decor brand with collections in ceramics, textiles, and artisan furniture.",
    recentNews: "Crossed 500k Pinterest followers; launched wholesale portal for boutique retailers.",
    pipelineStage: "discovered",
    saved: false
  },
  // ── CUSTOM SCRAPER / WEB CRAWL ────────────────────────────────────────────
  {
    id: "lead_033",
    name: "Igor Petrov",
    title: "Founder & CEO",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #8B5CF6, #06B6D4)",
    company: "ColdStart Growth",
    domain: "coldstart.agency",
    industry: "Digital Agency",
    companySize: "11-50",
    headcount: 18,
    revenue: "$2.9M Annual",
    fundingStage: "Bootstrap",
    location: "Amsterdam, Netherlands",
    region: "Europe",
    email: "igor@coldstart.agency",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.2,
    phone: "+31 20 845 3311",
    linkedin: "https://linkedin.com/in/igor-petrov-growth",
    twitterHandle: "@igor_coldstart",
    sourcePlatform: "Custom Scraper",
    sourceUrl: "https://coldstart.agency",
    aiScore: 91,
    scoreTier: "high",
    intentSignal: "Web crawler: updated website stack from Webflow to Next.js — tech expansion signal; mailto links found",
    intentCategory: "tech_expansion",
    techStack: ["Next.js", "HubSpot", "Clay", "Instantly.ai", "Notion", "Slack"],
    companyBio: "Outbound cold email specialists helping European B2B agencies build predictable top-of-funnel pipeline.",
    recentNews: "Launched a 30-day cold email bootcamp serving 400+ agency operators.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_034",
    name: "Nadia Obi",
    title: "Head of Partnerships",
    seniority: "Head/Manager",
    avatarBg: "linear-gradient(135deg, #8B5CF6, #F59E0B)",
    company: "AfriSaaS Collective",
    domain: "afrisaas.com",
    industry: "B2B SaaS",
    companySize: "11-50",
    headcount: 24,
    revenue: "$3.4M ARR",
    fundingStage: "Seed",
    location: "Nairobi, Kenya",
    region: "Global",
    email: "nadia@afrisaas.com",
    emailDeliverability: 96,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 96.7,
    phone: "+254 712 345 678",
    linkedin: "https://linkedin.com/in/nadia-obi-partnerships",
    twitterHandle: "@nadia_afrisaas",
    sourcePlatform: "Custom Scraper",
    sourceUrl: "https://afrisaas.com/team",
    aiScore: 89,
    scoreTier: "medium",
    intentSignal: "Domain crawler found 8 new job postings for sales & business development roles",
    intentCategory: "hiring",
    techStack: ["HubSpot", "Stripe", "AWS", "Intercom", "Notion", "Airtable"],
    companyBio: "Pan-African B2B SaaS community and marketplace connecting African startups with global enterprise procurement.",
    recentNews: "Partnered with Google for Startups Africa to support 200 early-stage founders.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_035",
    name: "Lucas Wagner",
    title: "VP of Sales & Alliances",
    seniority: "VP/Director",
    avatarBg: "linear-gradient(135deg, #8B5CF6, #3B82F6)",
    company: "StackPilot DevOps",
    domain: "stackpilot.dev",
    industry: "Cloud Infrastructure",
    companySize: "51-200",
    headcount: 105,
    revenue: "$22.1M ARR",
    fundingStage: "Series A",
    location: "Vienna, Austria",
    region: "Europe",
    email: "l.wagner@stackpilot.dev",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.4,
    phone: "+43 1 5045 6812",
    linkedin: "https://linkedin.com/in/lucas-wagner-devops",
    twitterHandle: "@lucas_devops",
    sourcePlatform: "Custom Scraper",
    sourceUrl: "https://stackpilot.dev/about",
    aiScore: 93,
    scoreTier: "high",
    intentSignal: "Web crawl: published 3 new blog posts about Kubernetes migration and GitOps patterns in last 7 days",
    intentCategory: "tech_expansion",
    techStack: ["Kubernetes", "ArgoCD", "Terraform", "AWS", "Datadog", "Grafana"],
    companyBio: "GitOps-native platform for infrastructure delivery automation and developer self-service.",
    recentNews: "Reached 300+ enterprise engineering teams on platform.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_036",
    name: "Priya Nair",
    title: "VP of Marketing",
    seniority: "VP/Director",
    avatarBg: "linear-gradient(135deg, #6366F1, #EC4899)",
    company: "Nexlify",
    domain: "nexlify.com",
    industry: "B2B SaaS",
    companySize: "51-200",
    headcount: 110,
    revenue: "$19.4M ARR",
    fundingStage: "Series B",
    location: "San Jose, US",
    region: "North America",
    email: "priya.n@nexlify.com",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.3,
    phone: "+1 (669) 221-8870",
    linkedin: "https://linkedin.com/in/priya-nair-marketing",
    twitterHandle: "@priya_nexlify",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/priya-nair-marketing",
    aiScore: 96,
    scoreTier: "ultra",
    intentSignal: "Announced $12M Series B; scaling GTM and content pipeline for enterprise segment",
    intentCategory: "funding",
    techStack: ["HubSpot", "Salesforce", "Marketo", "Demandbase", "Gong", "Drift"],
    companyBio: "AI-powered project management platform for cross-functional enterprise product teams.",
    recentNews: "Launched Nexlify Enterprise Tier with SOC2 compliance and SSO.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_037",
    name: "Thomas Berger",
    title: "Chief Technology Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #3B82F6, #F59E0B)",
    company: "DataVault EU",
    domain: "datavault.eu",
    industry: "Cybersecurity",
    companySize: "51-200",
    headcount: 95,
    revenue: "$17.8M ARR",
    fundingStage: "Series A",
    location: "Munich, Germany",
    region: "Europe",
    email: "t.berger@datavault.eu",
    emailDeliverability: 97,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 97.0,
    phone: "+49 89 3871 5502",
    linkedin: "https://linkedin.com/in/thomas-berger-cto",
    twitterHandle: "@tberger_dv",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/thomas-berger-cto",
    aiScore: 92,
    scoreTier: "high",
    intentSignal: "Migrating from on-premise to SaaS architecture; evaluating zero-trust identity stack",
    intentCategory: "tech_expansion",
    techStack: ["Okta", "Zscaler", "Azure AD", "Terraform", "CrowdStrike", "Splunk"],
    companyBio: "GDPR-compliant enterprise data vaulting and encryption-at-rest infrastructure for European banks.",
    recentNews: "Gained BaFin regulatory approval for banking-grade encryption certification.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_038",
    name: "Carlos Rivera",
    title: "Chief Revenue Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #10B981, #F43F5E)",
    company: "TradeFlux",
    domain: "tradeflux.io",
    industry: "Fintech",
    companySize: "201-500",
    headcount: 265,
    revenue: "$45.7M ARR",
    fundingStage: "Series B",
    location: "Miami, US",
    region: "North America",
    email: "c.rivera@tradeflux.io",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.9,
    phone: "+1 (305) 412-6690",
    linkedin: "https://linkedin.com/in/carlos-rivera-cro",
    twitterHandle: "@carlos_tradeflux",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/carlos-rivera-cro",
    aiScore: 96,
    scoreTier: "ultra",
    intentSignal: "Expanding into Latin American SMB market; hiring 30 enterprise AEs with B2B fintech experience",
    intentCategory: "hiring",
    techStack: ["Salesforce", "Outreach.io", "Gong", "ZoomInfo", "Snowflake", "Stripe"],
    companyBio: "Real-time FX and trade finance platform for SMB importers and exporters across 45 countries.",
    recentNews: "Processed $2B in trade volume in Q2 2026 — record quarter.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_039",
    name: "Sara Lindberg",
    title: "Head of Growth Marketing",
    seniority: "Head/Manager",
    avatarBg: "linear-gradient(135deg, #06B6D4, #F59E0B)",
    company: "Momentum Commerce",
    domain: "momentum.co",
    industry: "E-Commerce",
    companySize: "51-200",
    headcount: 88,
    revenue: "$28.2M GMV",
    fundingStage: "Series A",
    location: "Stockholm, Sweden",
    region: "Europe",
    email: "sara.l@momentum.co",
    emailDeliverability: 98,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 98.1,
    phone: "+46 70 334 5512",
    linkedin: "https://linkedin.com/in/sara-lindberg-growth",
    twitterHandle: "@sara_momentum",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/sara-lindberg-growth",
    aiScore: 91,
    scoreTier: "high",
    intentSignal: "Doubling D2C marketing budget for Q4 BFCM season; hiring performance marketers",
    intentCategory: "hiring",
    techStack: ["Klaviyo", "Google Ads", "TikTok Ads", "Shopify Plus", "Gorgias", "Northbeam"],
    companyBio: "Full-funnel commerce growth platform helping Nordic DTC brands scale internationally.",
    recentNews: "Acquired Swede Digital, expanding into influencer and affiliate marketing services.",
    pipelineStage: "discovered",
    saved: false
  },
  {
    id: "lead_040",
    name: "Ravi Shankar",
    title: "Chief AI Officer",
    seniority: "C-Level",
    avatarBg: "linear-gradient(135deg, #6366F1, #F59E0B)",
    company: "OracleEdge Analytics",
    domain: "oracleedge.ai",
    industry: "AI & ML",
    companySize: "201-500",
    headcount: 320,
    revenue: "$67.4M ARR",
    fundingStage: "Series C",
    location: "Bangalore, India",
    region: "APAC",
    email: "ravi.s@oracleedge.ai",
    emailDeliverability: 99,
    emailStatus: "Verified",
    mxValid: true,
    smtpCheck: true,
    deliverabilityScore: 99.4,
    phone: "+91 80 6765 2211",
    linkedin: "https://linkedin.com/in/ravi-shankar-ai",
    twitterHandle: "@ravi_oracleedge",
    sourcePlatform: "LinkedIn",
    sourceUrl: "https://linkedin.com/in/ravi-shankar-ai",
    aiScore: 98,
    scoreTier: "ultra",
    intentSignal: "Launched LLM fine-tuning vertical for banking and insurance clients; seeking enterprise data partners",
    intentCategory: "product_launch",
    techStack: ["AWS Bedrock", "Python", "Databricks", "Snowflake", "OpenAI API", "Salesforce", "Tableau"],
    companyBio: "AI-native business intelligence and predictive analytics platform for enterprise financial services.",
    recentNews: "Signed 5-year data partnership with HDFC Bank and ICICI Securities.",
    pipelineStage: "discovered",
    saved: true
  }
];

export const INDUSTRY_OPTIONS = [
  "B2B SaaS",
  "AI & ML",
  "Fintech",
  "E-Commerce",
  "Cybersecurity",
  "HealthTech",
  "Digital Agency",
  "Cloud Infrastructure",
  "Real Estate"
];

export const COMPANY_SIZE_OPTIONS = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "500+"
];

export const REGION_OPTIONS = [
  "North America",
  "Europe",
  "APAC",
  "Global"
];

export const SENIORITY_OPTIONS = [
  "C-Level",
  "VP/Director",
  "Head/Manager"
];

export const INTENT_OPTIONS = [
  { id: "funding", label: "Series A-C Funding Raised" },
  { id: "hiring", label: "Aggressive Hiring / Team Surge" },
  { id: "tech_expansion", label: "Tech Stack & Tool Migration" },
  { id: "product_launch", label: "New Market / Product Launch" }
];

export const SOURCE_PLATFORM_OPTIONS = [
  "LinkedIn",
  "Twitter",
  "Upwork",
  "Facebook",
  "Pinterest",
  "Custom Scraper",
  "Apollo"
];

export const EMAIL_STATUS_OPTIONS = [
  { id: "Verified", label: "Verified (250 OK)" },
  { id: "Catch-All", label: "Catch-All Server" },
  { id: "Unverified", label: "Unverified" },
  { id: "Invalid", label: "Invalid / Bounced" }
];

export const FUNDING_STAGE_OPTIONS = [
  "Bootstrap",
  "Seed",
  "Series A",
  "Series B",
  "Series C"
];
